events {}

http {
    upstream store_api {
        server store-api:8080;
    }

    server {
        listen 8080;

        location / {
            proxy_pass http://store_api;
            proxy_set_header X-TENANT-ID "bob";
            proxy_set_header X-REQUEST-ID "store-api-$request_id";
        }
    }
}