{
 "title": "Store Metrics",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "metrics", "query": "prometheus" }
  ]
 },
 "panels": [
  { "title": "Summary", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Services",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "targets": [
    { "expr": "build_info" }
   ]
  },
  {
   "title": "Messages Stored",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "messages" } },
   "targets": [
    {
     "expr": "messages_stored{service=\"store\",component=\"receiver\"}"
    }
   ]
  },
  {
   "title": "Latency",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "avg(rate(request_duration_seconds_sum{}[$__rate_interval])/rate(request_duration_seconds_count{}[$__rate_interval])) by (service, component,handler)",
     "legendFormat": "{{ service }}.{{ component }}.{{ handler }}"
    }
   ]
  },
  { "title": "Store Stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Messages Queue To Save",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "messages" } },
   "targets": [
    {
     "expr": "sum by(component) (message_received_queue_size)",
     "legendFormat": "current"
    },
    {
     "expr": "sum by (component) (messages_received_queue_capacity)",
     "legendFormat": "max"
    }
   ]
  },
  {
   "title": "Messages Updated",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "messages" } },
   "targets": [
    {
     "expr": "increase(messages_updated_count[1m])",
     "legendFormat": "{{ component }}"
    }
   ]
  },
  { "title": "Store Latency", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 } },
  {
   "title": "API Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "max(rate(request_duration_seconds_sum{service=\"store\",component=\"api\"}[$__rate_interval])/rate(request_duration_seconds_count{service=\"store\",component=\"api\"}[$__rate_interval])) by (handler)",
     "legendFormat": "{{ handler }}"
    }
   ]
  },
  {
   "title": "Receiver Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "max(rate(request_duration_seconds_sum{service=\"store\",component=\"receiver\"}[$__rate_interval])/rate(request_duration_seconds_count{service=\"store\",component=\"receiver\"}[$__rate_interval])) by (handler)",
     "legendFormat": "{{ handler }}"
    }
   ]
  },
  {
   "title": "API Controller Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "max(rate(controller_method_duration_seconds_sum{service=\"store\",component=\"api\"}[$__rate_interval])/rate(controller_method_duration_seconds_count{service=\"store\",component=\"api\"}[$__rate_interval])) by (caller_id)",
     "legendFormat": "{{ caller_id }}"
    }
   ]
  },
  {
   "title": "Receiver Controller Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "max(rate(controller_method_duration_seconds_sum{service=\"store\",component=\"receiver\"}[$__rate_interval])/rate(controller_method_duration_seconds_count{service=\"store\",component=\"receiver\"}[$__rate_interval])) by (caller_id)",
     "legendFormat": "{{ caller_id }}"
    }
   ]
  },
  { "title": "Sender", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 35 } },
  {
   "title": "Messages Failed to Send",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 36 },
   "targets": [
    {
     "expr": "sum(increase(messages_failed_count[1m])) by (tenant_id)",
     "legendFormat": "{{ tenant_id }}"
    }
   ]
  },
  {
   "title": "Messages Sent by Tenant",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 36 },
   "targets": [
    {
     "expr": "sum(increase(messages_sent_count[1m])) by (tenant_id)",
     "legendFormat": "{{ tenant_id }}"
    }
   ]
  },
  {
   "title": "Registry Tenants",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "tenants" } },
   "targets": [
    {
     "expr": "registry_tenants{service=\"sender\"}",
     "legendFormat": "{{ service }}"
    }
   ]
  },
  { "title": "Performance", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 44 } },
  {
   "title": "Memory Consumption",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum(process_resident_memory_bytes) by (job)",
     "legendFormat": "{{ job }}"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum(rate(process_cpu_seconds_total[5m])*100) by (job)",
     "legendFormat": "{{ job }}"
    }
   ]
  }
 ]
}